# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EnglishName' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EnglishName

  target 'EnglishNameTests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'CodePush', :path => ‘../node_modules/react-native-code-push'
end
